name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    name: Deploy to EC2 Instance
    runs-on: ubuntu-latest


    steps:

      - name: Deploy in EC2
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.HOST_DNS }}  >> ~/.ssh/known_hosts
          cat ~/.ssh/id_rsa
          chmod +x ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: | 
           pwd
           mkdir aa
           rsync -avz ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:/home/ubuntu/ci/


      - name: copying files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            git clone https://github.com/imJunaidAfzal/ci-cd-pipeline-django.git
            cd ci-cd-pipeline-django
            python manage.py runserver 0.0.0.0:8000
